import 'package:flutter/material.dart';
import 'package:flutter_intl_phone_field/countries.dart';

const List<Country> arabicCountries = [
  Country(
    name: 'United Arab Emirates',
    code: 'AE',
    dialCode: '971',
    minLength: 9,
    maxLength: 9,
    flag: '🇦🇪',
    nameTranslations: {'ar': 'الإمارات', 'en': 'United Arab Emirates'},
  ),
  Country(
    name: 'Bahrain',
    code: 'BH',
    dialCode: '973',
    minLength: 8,
    maxLength: 8,
    flag: '🇧🇭',
    nameTranslations: {'ar': 'البحرين', 'en': 'Bahrain'},
  ),
  Country(
    name: 'Algeria',
    code: 'DZ',
    dialCode: '213',
    minLength: 9,
    maxLength: 9,
    flag: '🇩🇿',
    nameTranslations: {'ar': 'الجزائر', 'en': 'Algeria'},
  ),
  Country(
    name: 'Saudi Arabia',
    code: 'SA',
    dialCode: '966',
    minLength: 9,
    maxLength: 9,
    flag: '🇸🇦',
    nameTranslations: {'ar': 'السعودية', 'en': 'Saudi Arabia'},
  ),
  Country(
    name: 'Iraq',
    code: 'IQ',
    dialCode: '964',
    minLength: 10,
    maxLength: 10,
    flag: '🇮🇶',
    nameTranslations: {'ar': 'العراق', 'en': 'Iraq'},
  ),
  Country(
    name: 'Oman',
    code: 'OM',
    dialCode: '968',
    minLength: 8,
    maxLength: 8,
    flag: '🇴🇲',
    nameTranslations: {'ar': 'عمان', 'en': 'Oman'},
  ),
  Country(
    name: 'Palestine',
    code: 'PS',
    dialCode: '970',
    minLength: 9,
    maxLength: 9,
    flag: '🇵🇸',
    nameTranslations: {'ar': 'فلسطين', 'en': 'Palestine'},
  ),
  Country(
    name: 'Qatar',
    code: 'QA',
    dialCode: '974',
    minLength: 8,
    maxLength: 8,
    flag: '🇶🇦',
    nameTranslations: {'ar': 'قطر', 'en': 'Qatar'},
  ),
  Country(
    name: 'Kuwait',
    code: 'KW',
    dialCode: '965',
    minLength: 8,
    maxLength: 8,
    flag: '🇰🇼',
    nameTranslations: {'ar': 'الكويت', 'en': 'Kuwait'},
  ),
  Country(
    name: 'Libya',
    code: 'LY',
    dialCode: '218',
    minLength: 9,
    maxLength: 9,
    flag: '🇱🇾',
    nameTranslations: {'ar': 'ليبيا', 'en': 'Libya'},
  ),
  Country(
    name: 'Lebanon',
    code: 'LB',
    dialCode: '961',
    minLength: 8,
    maxLength: 8,
    flag: '🇱🇧',
    nameTranslations: {'ar': 'لبنان', 'en': 'Lebanon'},
  ),
  Country(
    name: 'Morocco',
    code: 'MA',
    dialCode: '212',
    minLength: 9,
    maxLength: 9,
    flag: '🇲🇦',
    nameTranslations: {'ar': 'المغرب', 'en': 'Morocco'},
  ),
  Country(
    name: 'Mauritania',
    code: 'MR',
    dialCode: '222',
    minLength: 8,
    maxLength: 8,
    flag: '🇲🇷',
    nameTranslations: {'ar': 'موريتانيا', 'en': 'Mauritania'},
  ),
  Country(
    name: 'Syria',
    code: 'SY',
    dialCode: '963',
    minLength: 9,
    maxLength: 9,
    flag: '🇸🇾',
    nameTranslations: {'ar': 'سوريا', 'en': 'Syria'},
  ),
  Country(
    name: 'Tunisia',
    code: 'TN',
    dialCode: '216',
    minLength: 8,
    maxLength: 8,
    flag: '🇹🇳',
    nameTranslations: {'ar': 'تونس', 'en': 'Tunisia'},
  ),
  Country(
    name: 'Yemen',
    code: 'YE',
    dialCode: '967',
    minLength: 9,
    maxLength: 9,
    flag: '🇾🇪',
    nameTranslations: {'ar': 'اليمن', 'en': 'Yemen'},
  ),
  Country(
    name: 'Djibouti',
    code: 'DJ',
    dialCode: '253',
    minLength: 8,
    maxLength: 8,
    flag: '🇩🇯',
    nameTranslations: {'ar': 'جيبوتي', 'en': 'Djibouti'},
  ),
  Country(
    name: 'Comoros',
    code: 'KM',
    dialCode: '269',
    minLength: 7,
    maxLength: 7,
    flag: '🇰🇲',
    nameTranslations: {'ar': 'جزر القمر', 'en': 'Comoros'},
  ),
  Country(
    name: 'Somalia',
    code: 'SO',
    dialCode: '252',
    minLength: 8,
    maxLength: 8,
    flag: '🇸🇴',
    nameTranslations: {'ar': 'الصومال', 'en': 'Somalia'},
  ),
  Country(
    name: 'Somalia',
    code: 'SO',
    dialCode: '252',
    minLength: 8,
    maxLength: 8,
    flag: '🇸🇴',
    nameTranslations: {'ar': 'الصومال', 'en': 'Somalia'},
  ),
  Country(
    name: 'Egypt',
    code: 'EG',
    dialCode: '20',
    minLength: 10,
    maxLength: 10,
    flag: '🇪🇬',
    nameTranslations: {'ar': 'مصر', 'en': 'Egypt'},
  ),
];

List<Country> getLocalizedCountries(BuildContext context) {
  final locale = Localizations.localeOf(context);
  final isArabic = locale.languageCode == 'ar';

  return arabicCountries.map((c) {
    return Country(
      name: isArabic ? c.nameTranslations['ar']! : c.name,
      code: c.code,
      dialCode: c.dialCode,
      minLength: c.minLength,
      maxLength: c.maxLength,
      flag: c.flag,
      nameTranslations: c.nameTranslations,
      regionCode: c.regionCode,
    );
  }).toList();
}
