// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JzxKpOMGXmvC0ADDiWLf5WKKTg01i6U',
    appId: '1:200274876402:android:2576bff35d2ab97cacbd6b',
    messagingSenderId: '200274876402',
    projectId: 'mokawlcom-app',
    storageBucket: 'mokawlcom-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3GBbmSBfzbOjkLKm9PFIUEIkDZ9l7So',
    appId: '1:200274876402:ios:ebbcf8e109f1aef1acbd6b',
    messagingSenderId: '200274876402',
    projectId: 'mokawlcom-app',
    storageBucket: 'mokawlcom-app.firebasestorage.app',
    androidClientId: '200274876402-q9f1ido2dvotit0uaqunr3jeoe908ofj.apps.googleusercontent.com',
    iosClientId: '200274876402-cmmluti6dskuq8shqk0qnphr9bc45agd.apps.googleusercontent.com',
    iosBundleId: 'com.mokawlcomapp.mokawlcom',
  );

}